name: Build Docker Image (Production)

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Metadata: Git"
        id: git-meta
        run: |
          echo "dockertag=xacademy-docker.pkg.coding.net/ai-dating/nextjs_fullstack/server:master-${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: "Docker: Setup Buildx"
        uses: docker/setup-buildx-action@v2

      - name: "Login to CODING.net Registry"
        uses: docker/login-action@v2
        with:
          registry: xacademy-docker.pkg.coding.net
          username: ${{ secrets.CODING_MIRRO_DOCKER_PKG_USERNAME }}
          password: ${{ secrets.CODING_MIRRO_DOCKER_PKG_PASSWORD }}

      - name: "Docker: Build and Push Image"
        id: ghcr-docker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.git-meta.outputs.dockertag }}

      - name: "ManifestBot: Checkout"
        uses: actions/checkout@v3
        with:
          repository: "techx-academy/actions"
          token: "${{ secrets.PAT_FOR_MANIFESTS }}"
          path: "./.github/actions"

      - name: "ManifestBot: Dispatch new version"
        uses: "./.github/actions/manifestbot"
        with:
          file-path: "applications/mirro/values-prod.yaml"
          version: ${{ steps.git-meta.outputs.dockertag }}
